### ISSUE TITLE
nn module with tensorflow

### ISSUE THREAD

**Issue by SeekPoint** [yyaghoobzadeh/figment-multi#2]
(.venv) ub16hp@UB16HP:~/ub16_prj/figment-multi$ pip install nn
Collecting nn
  Downloading https://files.pythonhosted.org/packages/32/5b/4ff7a1bdc8e30e260c4dd44343275c50497b9db9fd96100fef1b7ca8a2b6/nn-0.0.9.tar.gz
Building wheels for collected packages: nn
  Running setup.py bdist_wheel for nn ... done
  Stored in directory: /home/ub16hp/.cache/pip/wheels/61/36/72/2ccb1d96aae93cf0e1de5b84c0c953de38dc5a152011c4a7f6
Successfully built nn
Installing collected packages: nn
Successfully installed nn-0.0.9
(.venv) ub16hp@UB16HP:~/ub16_prj/figment-multi$ bash run_a_model.sh swlr
Traceback (most recent call last):
  File "../../src/train_test.py", line 26, in <module>
    from nn import track_best, MainLoop
  File "/home/ub16hp/ub16_prj/figment-multi/.venv/local/lib/python2.7/site-packages/nn/__init__.py", line 1, in <module>
    from .layers import *
  File "/home/ub16hp/ub16_prj/figment-multi/.venv/local/lib/python2.7/site-packages/nn/layers/__init__.py", line 1, in <module>
    from tensorflow.python.layers.layers import *
ImportError: No module named tensorflow.python.layers.layers
(.venv) ub16hp@UB16HP:~/ub16_prj/figment-multi$

**Comment by yyaghoobzadeh** [comment]
I've updated the code. That shouldn't be a problem anymore.
